### POST Create a new patient entity

###http://lb-7e648e08.elb.localhost.localstack.cloud:4004/api/patients
POST http://localhost:4000/patients
Content-Type: application/json
##Authorization: Bearer {{token}}

{
"name": "John Doe Kafka_test",
"email": "test2_Kafka_test@email.com",
  "address": "123 Main",
  "dateOfBirth": "1995-05-21",
  "registeredDate": "2024-08-27"
}

###